version: "3.8"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: run.sh
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
